config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  # resources :tickets
  resources :kanbans, except: [:index] do
    get '/kanbans', to: 'dashboards#index'

    resources :columns, except: [:new, :edit] do
      member do
        put 'drag'
      end
    end
    resources :tickets, only: [:create, :update, :destroy] do
      member do
        put 'drag'
      end
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get 'dashboard', to: "pages#dashboard"
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :kanban
  acts_as_list scope: :kanban

  has_many :tickets, -> { order(position: :asc) }, dependent: :destroy
  

  validates_presence_of :name, on: [:create, :update], message: "不可以空白"
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: %i[drag show edit update destroy]

  def drag
    @column.insert_at(params[:position].to_i)
    kanban_id = @column.kanban_id
    params = JSON.parse(@column.kanban.columns.to_json)
    ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'success', message: 'A card being moved' } })
    ActionCable.server.broadcast("column", { commit: 'REPOSITION_COLUMN', payload: params })
    render 'show.json'
  end

  # GET /columns or /columns.json
  def index
    @kanban = Kanban.find(params[:kanban_id])
    @columns = @kanban.columns
  end

  # GET /columns/1 or /columns/1.json
  def show; end

  # GET /columns/new
  def new
    @column = Column.new
  end

  # GET /columns/1/edit
  def edit; end

  # POST /columns or /columns.json
  def create
    @column = Column.new(column_params)
    if @column.save
      column = JSON.parse(@column.to_json)
      kanban_id = @column.kanban_id
      ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'success', message: 'A card being created' } })
      ActionCable.server.broadcast("column", { commit: 'ADD_COLUMN', payload: column })
      render json: @column, status: :ok
    else
      render json: @column.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /columns/1 or /columns/1.json
  def update
    if @column.update(column_params)
      column = JSON.parse(@column.to_json)
      kanban_id = @column.kanban_id
      ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'success', message: 'A card being updated' } })
      ActionCable.server.broadcast("column", { commit: 'UPDATE_COLUMN', payload: column })
      render json: @column, status: :ok
    else
      render json: @column.errors, status: :unprocessable_entity
    end
  end

  # DELETE /columns/1 or /columns/1.json
  def destroy
    column = JSON.parse(@column.to_json)
    if @column.destroy
      ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'error', message: 'A card being removed' } })
      ActionCable.server.broadcast('column', { commit: 'DELETE_COLUMN', payload: column })
      render json: { head: :no_content }, status: :ok
    else
      render json: @column.errors, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_column
    @column = Column.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def column_params
    params.require(:column).permit(:name, :kanban_id, :position)
  end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/_form.html.erb
<%= form_with(model: column, local: true) do |form| %>
  <% if column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
        <% column.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :kanban_id %>
    <%= form.text_field :kanban_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing Column</h1>

<%= render 'form', column: @column %>

<%= link_to 'Show', @column %> |
<%= link_to 'Back', columns_path %>

app/views/columns/index.html.erb
<div id="column" class="h-full bg-trueGray-100 w-full overflow-auto" data-kanbanid="<%= @kanban.id %>">
  <div class="board p-4 bg-gray-100 h-full w-full">
    <div class="flex flex-row items-start">
      <draggable v-model="columns" @change="dropColumn" ghost-class="ghost-card" :move="checkMove" class="">
        <transition-group  class="flex">
          <board-column v-for="column in columns" :column="column" :key="column.id" class="mr-4" />
        </transition-group>
      </draggable>  
      <div class="column bg-gray-200 p-2 text-left shadow rounded border-2 border-coolGray-300">
        <h4 class="mb-2 font-bold">Create Card</h4>
        <input
          type="text"
          class="p-2 mr-2 flex-grow w-full block rounded bg-gray-100"
          v-model="newColumnName"
          placeholder="Enter to card title"
          @keyup.enter="createColumn"
        />
      </div>
      <div class="spacer"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="></div>
    </div>
  </div>
</div>

app/views/columns/new.html.erb
<h1>New Column</h1>

<%= render 'form', column: @column %>

<%= link_to 'Back', columns_path %>