config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  # resources :tickets
  resources :kanbans, except: [:index] do
    get '/kanbans', to: 'dashboards#index'

    resources :columns, except: [:new, :edit] do
      member do
        put 'drag'
      end
    end
    resources :tickets, only: [:create, :update, :destroy] do
      member do
        put 'drag'
      end
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get 'dashboard', to: "pages#dashboard"
end

app/views/pages/dashboard.html.erb
<div class="container px-4 sm:px-8 lg:px-8 xl:px-16 mx-auto">
  <section class="section hero text-center">
    <h1 class="title text-xl mt-5">Welcome to <%= current_user.display_name%>'s' Task Manager！</h1>
    <br>
    <%= link_to 'Create Kanban', new_kanban_path, class: "font-light button border-2 border-gray-100 bg-gray-100 hover:bg-coolGray-50 hover:border-transparent shadow py-2 px-3 rounded" %>
    <div class="text-md flex p-4 mt-4">
      <div class="flex flex-wrap justify-start">
        <% @kanbans.each do |kanban| %>
          <div class="">
            <%= link_to "Edit", edit_kanban_path(kanban), class: "block text-right mr-2 text-sm m-0 p-0" %>
            <%= link_to kanban_columns_path(kanban) do %>
              <article class=" h-72 w-80 m-2 mt-0 border-2 border-warmGray-100 p-2 rounded-md bg-white shadow-sm hover:shadow">
                <header class="relative">

                  <div class="rounded-t-lg object-cover h-36 w-full bg-warmGray-500"></div>
                  <h2 class="absolute left-0 right-0 top-1/2 bottom-1/2 text-white text-lg font-bold tracking-wide hover:bg-transparent hover:text-gray-200">
                    <%= kanban.name %>
                  </h2>
                </header>
                <section>
                  <p class="mt-2 h-28 text-gray-700 text-sm overflow-scroll overflow-y-auto tracking-wide">
                    <%= kanban.description %>
                  </p>
                </section>
              </article>
            <% end %>
          </div>
        <% end %>
      </div>
    </div> 
  </section>
</div>