config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  # resources :tickets
  resources :kanbans, except: [:index] do
    get '/kanbans', to: 'dashboards#index'

    resources :columns, except: [:new, :edit] do
      member do
        put 'drag'
      end
    end
    resources :tickets, only: [:create, :update, :destroy] do
      member do
        put 'drag'
      end
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get 'dashboard', to: "pages#dashboard"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :column
  acts_as_list scope: :column

  validates_presence_of :name, on: [:create, :update], message: "不可以空白"
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[drag show edit update destroy]

  def drag
    kanban_id = @ticket.column.kanban_id
    old_column_id = @ticket.column_id
    if @ticket.update(ticket_params)
      old_col_tickets = Column.find(old_column_id).tickets
      new_ticket = JSON.parse(@ticket.to_json)
      new_col_tickets = JSON.parse(@ticket.column.tickets.to_json)
      case params[:behavior]
      when 'moved'
        ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'success', message: 'A ticket being shifted' } })
        ActionCable.server.broadcast("column", { commit: 'REORDER_TICKET', payload: { kanbanId: kanban_id, ticket: new_ticket, newTickets: new_col_tickets } })
      when 'added'
        # 轉移 ticket 至其他 column
        ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'success', message: 'A ticket being transfered to another card' } })
        ActionCable.server.broadcast("column",
                                     { commit: 'TRANSFER_TICKET',
                                       payload: {
                                        kanbanId: kanban_id,
                                         old_column_id: old_column_id,
                                         ticket: new_ticket,
                                         oldTickets: old_col_tickets,
                                         newTickets: new_col_tickets
                                       } })
      end
      render json: @ticket, status: :ok
    else
      render json: @ticket.errors, status: :unprocessable_entity
    end
  end

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show; end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit; end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    kanban_id = @ticket.column.kanban_id

    if @ticket.save
      ticket = JSON.parse(@ticket.to_json)
      ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'success', message: 'A ticket being created' } })
      ActionCable.server.broadcast("column",
                                   { commit: 'ADD_TICKET', payload: ticket })
      render json: @ticket, status: :ok
    else
      render json: @ticket.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    if @ticket.update(ticket_params)
      kanban_id = @ticket.column.kanban_id
      ticket = JSON.parse(@ticket.to_json)
      ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'warning', message: 'A ticket being updated' } })
      ActionCable.server.broadcast("column",
                                   { commit: 'EDIT_TICKET', payload: ticket })
      render json: @ticket, status: :ok
    else
      render json: @ticket.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    ticket = JSON.parse(@ticket.to_json)
    if @ticket.destroy
      kanban_id = @ticket.column.kanban_id
      ActionCable.server.broadcast("flash:#{current_user.id}", { commit: 'PUSH_NOTICE', payload: { type: 'error', message: 'A ticket being deleted' } })
      ActionCable.server.broadcast("column",
                                   { commit: 'DELETE_TICKET', payload: ticket })
      render json: { head: :no_content }, status: :ok
    else
      render json: @ticket.errors, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ticket_params
    params.require(:ticket).permit(:name, :column_id, :position)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :column_id %>
    <%= form.text_field :column_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Column</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.column_id %></td>
        <td><%= ticket.position %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>