config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  # resources :tickets
  resources :kanbans, except: [:index] do
    get '/kanbans', to: 'dashboards#index'

    resources :columns, except: [:new, :edit] do
      member do
        put 'drag'
      end
    end
    resources :tickets, only: [:create, :update, :destroy] do
      member do
        put 'drag'
      end
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get 'dashboard', to: "pages#dashboard"
end

app/models/kanban.rb
class Kanban < ApplicationRecord
  belongs_to :user
  has_many :columns, -> { order(position: :asc) }, dependent: :destroy

  validates_presence_of :name, on: [:create, :update], message: "不可以空白"
end

app/controllers/kanbans_controller.rb
class KanbansController < ApplicationController
  before_action :set_kanban, only: %i[ show edit update destroy ]

  # GET /kanbans or /kanbans.json
  def index
    @kanbans = Kanban.all
  end

  # GET /kanbans/1 or /kanbans/1.json
  def show
  end

  # GET /kanbans/new
  def new
    # @kanban = Kanban.new
    @kanban = current_user.kanbans.new
  end

  # GET /kanbans/1/edit
  def edit
  end

  # POST /kanbans or /kanbans.json
  def create
    # @kanban = Kanban.new(kanban_params)
    @kanban = current_user.kanbans.new(kanban_params)

    respond_to do |format|
      if @kanban.save
        format.html { redirect_to root_path, success: "A Kanban being created" }
        format.json { render :show, status: :created, location: @kanban }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kanbans/1 or /kanbans/1.json
  def update
    respond_to do |format|
      if @kanban.update(kanban_params)
        format.html { redirect_to root_path, success: "A Kanban being updated" }
        format.json { render :show, status: :ok, location: @kanban }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kanbans/1 or /kanbans/1.json
  def destroy
    @kanban.destroy
    respond_to do |format|
      format.html { redirect_to kanbans_url, notice: "Kanban was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kanban
      @kanban = Kanban.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kanban_params
      params.require(:kanban).permit(:name, :description, :user_id)
    end
end

app/helpers/kanbans_helper.rb
module KanbansHelper
end

app/views/kanbans/_form.html.erb
      <%= form_with(model: kanban, local: true) do |f| %>
        <% if kanban.errors.any? %>
          <div id="error_explanation">
            <h2 class="text-sm text-red-400 mt-2"><%= pluralize(kanban.errors.count, "error") %> prohibited this kanban from being saved:</h2>

            <ul class="pl-4">
              <% kanban.errors.full_messages.each do |message| %>
                <li class="text-sm list-disc"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field mt-4">
          <%= f.label "Title", class: 'block text-xs font-semibold text-gray-600 uppercase' %>
          
          <%= f.text_field :name, class: 'block w-full py-1 px-3
                    text-gray-800 appearance-none
                    border-b-2 border-gray-100
                    focus:text-gray-500 focus:outline-none focus:border-gray-200' %>
        </div>

        <div class="field mt-4">
          <%= f.label "Description", class: 'block mt-2 text-xs font-semibold text-gray-600 uppercase' %>
          <%= f.text_area :description, class: 'block w-full py-3 px-3
                    text-gray-800 appearance-none
                    border-b-2 border-gray-100
                    focus:text-gray-500 focus:outline-none focus:border-gray-200' %>
        </div>

        

        <div class="actions">
          <%= f.submit "Submit", class: 'w-full py-3 mt-6 bg-gray-800 rounded-sm
                    font-medium text-white uppercase tracking-widest
                    focus:outline-none hover:bg-gray-700 hover:shadow-none' %>
        </div>
      <% end %>

app/views/kanbans/edit.html.erb
<div class="flex flex-col h-screen bg-gray-100 w-full">
  <div class="grid place-items-center mx-2 my-20">
    <div class="w-11/12 p-12 sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-4/12
                px-6 py-10 sm:px-10 sm:py-6
              bg-white rounded-lg shadow-md lg:shadow-lg"
    >
      <h2 class="text-center font-semibold text-3xl lg:text-3xl text-gray-800 uppercase">
        Edit
      </h2>
      <%= render 'form', kanban: @kanban %>
    </div>
      <div class="mt-2">
      <%= link_to 'Back', dashboard_path %>
    </div>
  </div>

</div>

app/views/kanbans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kanbans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kanbans.each do |kanban| %>
      <tr>
        <td><%= kanban.name %></td>
        <td><%= kanban.description %></td>
        <td><%= kanban.user_id %></td>
        <td><%= link_to 'Show', kanban %></td>
        <td><%= link_to 'Edit', edit_kanban_path(kanban) %></td>
        <td><%= link_to 'Destroy', kanban, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kanban', new_kanban_path %>

app/views/kanbans/new.html.erb
<div class="flex flex-col h-screen bg-gray-100 w-full">
  <div class="grid place-items-center mx-2 my-20">
    <div class="w-11/12 p-12 sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-4/12
                px-6 py-10 sm:px-10 sm:py-6
              bg-white rounded-lg shadow-md lg:shadow-lg"
    >
      <h2 class="text-center font-semibold text-3xl lg:text-3xl text-gray-800 uppercase">
        Create Kanban
      </h2>

      

<%= render 'form', kanban: @kanban %>
      
    </div>
  </div>
</div>



<%= link_to 'Back', kanbans_path %>

app/views/kanbans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kanban.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @kanban.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @kanban.user_id %>
</p>

<%= link_to 'Edit', edit_kanban_path(@kanban) %> |
<%= link_to 'Back', kanbans_path %>